config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => "user/registrations" }
  resources :users, only: [:show, :index, :destroy]
  resources :photos
  
  resources :photos do 
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end
  
  resources :posts, only: [:create, :destroy]
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :relationships, only: [:create, :destroy]

  root 'welcome#index'
  get ':user_name', to: 'users#show', as: :profile
  get ':user_name/following', to: 'users#following', as: :following
  get ':user_name/followers', to: 'users#followers', as: :followers
    

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_photo

  def create 
    @comment = @photo.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
        
      respond_to do |format|
        format.html { redirect_to photo_path(@photo) }
        #format.js
      end
    else
       flash[:alert] = "Check the comment form, something went horribly wrong."
       render root_path
    end
  end
  

  def destroy 
    @comment = @photo.comments.find(params[:id])

    if @comment.user_id == current_user.id
        @comment.destroy

        respond_to do |format|
            format.html { redirect_to photo_path(@photo) }
            #format.js
        end
    end 
  end

 

  private

    def comment_params 
      params.require(:comment).permit(:content)
    end

    def set_photo 
      @photo = Photo.find(params[:photo_id])
    end
    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% unless @photo.comments.blank? %>
  <% @photo.comments.each do |comment| %>
    <div>
      <div class="commenter-name">
        <%= link_to comment.user.user_name, profile_path(comment.user.user_name) %>
      </div>
      <span class="comment">
        <%= comment.content %>
        <%= link_to ("<i class='fa fa-trash-o pull-right'></i>").html_safe, photo_comment_path(@photo, comment), method: :delete, data: { confirm: "Are you sure?" } %>
      </span>
    </div>
  <% end %>

<% else %> 
 <%= " Be the first one to comment. " %>
<% end %>

app/views/comments/_form.html.erb
<% if current_user %>
  <div class="comment-form">
    <div class="col-md-4 no-padding">
      <%= simple_form_for [@photo, @photo.comments.build] do |f| %>
        <%= f.text_field :content, placeholder: ' Add a comment...', :style => 'width: 285px; height: 25px; border:none' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/comments/create.js.erb
$('#comment_content_<%= @photo.id %>').val('')
$('#comment_content_<%= @photo.id %>').blur();
Append.comment_count += 1
$(Append.id).attr('data-value', Append.comment_count);

if (Append.comment || Append.open ){ $('#comments_<%= @photo.id %>').append("<%=j render 'comments/comment', photo: @photo, comment: @comment %>"); }

else if ((Append.comment && Append.open) === false && Append.link === true) { 
	$('#comments_' + Append.photo_id).append("<div class='paginator' id='#comments-paginator-" + Append.photo_id + "'><a class='more-comments' id='more_comments_" + Append.photo_id + "' data-photo-id='" + Append.photo_id + "' data-type='html' data-remote='true' data-value='" + Append.comment_count + "' href='/photos/" + Append.photo_id + "/comments'>view all " + Append.comment_count + " comments</a></div>"); 
	ClickableCommentsLink(); 
}

else if ((Append.comment && Append.open && Append.link) === false) { $('#more_comments_<%= @photo.id %>').html("view all <%= @photo.comments.count %> comments"); }

app/views/comments/destroy.js.erb
$('#comments_<%= @photo.id %>').html("<%= j render @photo.comments, photo: @photo, comment: @comment %>");
Append.comment_count -= 1