config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => "user/registrations" }
  resources :users, only: [:show, :index, :destroy]
  resources :photos
  
  resources :photos do 
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end
  
  resources :posts, only: [:create, :destroy]
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :relationships, only: [:create, :destroy]

  root 'welcome#index'
  get ':user_name', to: 'users#show', as: :profile
  get ':user_name/following', to: 'users#following', as: :following
  get ':user_name/followers', to: 'users#followers', as: :followers
    

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
         
  validates :user_name, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 15 }
  mount_uploader :avatar, AvatarUploader
  mount_uploader :cover, CoverUploader
  
  has_many :photos, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  acts_as_voter
  
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  
         
  def full_name
    return "#{first_name} #{last_name}".strip if (first_name || last_name)
    # if the user don't have a first or last name show as anonymous
    "Anonymous"
  end
  
     # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
    before_filter :configure_permitted_parameters

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up).push(:first_name, :last_name, :user_name, :avatar, :cover)
      devise_parameter_sanitizer.for(:account_update).push(:first_name, :last_name, :user_name, :avatar, :cover)
    end
    
    def after_update_path_for(resource)
      profile_path(@user.user_name)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :current_user, only: [:index, :edit, :update, :destroy]
    before_action :admin_user, only: :destroy
    
    def show
      @user = User.find_by(user_name: params[:user_name])
      @posts = @user.posts
    end
    
    def index
      @users = User.paginate(page: params[:page])
    end
    
    def destroy
      User.find(params[:id]).destroy
      flash[:success] = "User deleted"
      redirect_to users_url
    end
    
    def following
      @title = "Following"
      @user = User.find_by(user_name: params[:user_name])
      @users = @user.following.paginate(page: params[:page])
      render 'users/following/show_following'
    end

    def followers
      @title = "Followers"
      @user = User.find_by(user_name: params[:user_name])
      @users = @user.followers.paginate(page: params[:page])
      render 'users/following/show_followers'
    end
    
    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/views/users/_all_users.html.erb
<div class="total-width">
<%= will_paginate %>

<% @users.each do |user| %>
  <div class="col-md-3 all-users">
    <div class="avatar-area pull-left">
      <%#= gravatar_for user, size: 50 %>
      <%= link_to (image_tag user.avatar.url, size: "160x175"), profile_path(user.user_name) %>
    </div>
    <div class="name-area">
      <span class="name"><%= link_to user.full_name, profile_path(user.user_name) %></span></br>
      <span class="username">@<%= user.user_name %></span></br></br>
      <span class="stats"><i class="fa fa-male"></i> <%= user.followers.count %>
      <span class="red">&nbsp;|&nbsp;</span>
      <i class="fa fa-pencil"></i> <%= user.posts.count %>
      <span class="red">&nbsp;|&nbsp;</span>
      <i class="fa fa-picture-o"></i> <%= user.photos.count %></span></br></br>
        <%#= render 'users/following/follow_button' if current_user %>
      <span class="delete">
      <% if current_user.admin? %>  
        <%= link_to "remove user", user, method: :delete, data: { confirm: "You sure?" } %>
      <% end %>
      </span>
    </div>
  </div>
<% end %>

<%= will_paginate %>
</div>

app/views/users/index.html.erb
<%= render 'users/all_users' %>

app/views/users/show.html.erb
<!-- code start -->
<div class="p-div">
	
	<div>
		<%= link_to (image_tag @user.cover.url, size: "1138x350"), edit_registration_path(current_user), title: "Change Cover Picture" %>
	</div>

	<div class="p-stats">
		<ul> 
			<li>
				<span class="p-avatar", title="Upload a Picture"><%= link_to (image_tag @user.avatar.url, size: "200x220"), edit_registration_path(current_user) %></span>
			</li>
			<li>
				<span class="p-StatLabel p-block">Posts</span>
				<span class="p-StatValue"><%= link_to @user.posts.count, profile_path(@user.user_name) %></span>
			</li>
			<li>
				<span class="p-StatLabel p-block">Following</span>
				<span class="p-StatValue"><%= link_to @user.following.count, following_path(@user.user_name), id: "following" %></span>
			</li>
			<li>
				<span class="p-StatLabel p-block">Followers</span>
				<span class="p-StatValue"><%= link_to @user.followers.count, followers_path(@user.user_name), id: "followers" %></span>
			</li>
			<li class="p-btn-padding">
			  <%= render 'users/following/follow_button' if current_user %>
			</li>
		</ul>
	</div>

  <div class="p-name">
    <%= link_to @user.full_name, profile_path(@user.user_name) %>
  </div>
  <div class="p-username">
    @<%= link_to @user.user_name, profile_path(@user.user_name) %> 
  </div>
		
</div>
<!-- code end -->



<!-- start Left area -->
  <li class="left">
    <%= render 'users/profile_page/friends_list' %>
  </li>
<!-- end Left area -->

<!-- start Right area -->  
  <!-- start Post Form -->
  <li class="right">
    <%= render 'posts/form' %>
  </li>
  <!-- end Post Form -->
  <!-- start Posts -->
  <li class="right">
    <%= render 'posts/post' %>
  </li>
  <!-- end Posts -->
<!-- end Right area --> 