config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => "user/registrations" }
  resources :users, only: [:show, :index, :destroy]
  resources :photos
  
  resources :photos do 
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end
  
  resources :posts, only: [:create, :destroy]
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :relationships, only: [:create, :destroy]

  root 'welcome#index'
  get ':user_name', to: 'users#show', as: :profile
  get ':user_name/following', to: 'users#following', as: :following
  get ':user_name/followers', to: 'users#followers', as: :followers
    

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_login.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    
    <%= link_to ("<i class='fa fa-book'></i> " +'My Book').html_safe, root_path, class: "navbar-brand" %>
    
    <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div class="login-area top-padding pull-right">
        <ul>
          <li class="email-pad"> 
            <%= f.label :email %>
            <span class="input-clr">
              <%= f.email_field :email, autofocus: true %>
            </span>
            <% if devise_mapping.rememberable? %>
              <div class="checkbox remember-me">
                <%= f.label :remember_me do %>
                  <%= f.check_box :remember_me %>remember me
                <% end %>
              </div>
            <% end %>
          </li>
                  
          <li class="pass-pad">   
            <%= f.label :password %>
            <span class="input-clr">
              <%= f.password_field :password, autocomplete: "off", wrapper_html: { id: 'password' } %>
            </span>
            <% if devise_mapping.rememberable? %>
              <div class="forgot-password">
                <%= link_to t(".forgot_your_password", :default => "Forgot your password?"), new_password_path(resource_name) %>
              </div>
            <% end %>
          </li>
                  
          <li class="pull-right">
            <%= f.submit "Log In", class: 'btn btn-login' %>
          </li>
                  
        </ul>
      </div>
    <% end %> 
  </div>
</div>

app/views/welcome/_signup.erb
<div class="container">
  <div class="col-lg-4 no-padding pull-right">
    <%= bootstrap_devise_error_messages! %>
      <div class="signup-area">
        <div class="panel-heading">
          <h4>Create Your Account</h4>
        </div>
        <div class="panel-body">
          <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), html: { role: "form" }) do |f| %>
            <div class="form-group no-padding">
              <div class="col-sm-6 no-padding right-padding bottom-padding">
              <%= f.text_field :first_name, placeholder: 'First name', autofocus: true, class: "form-control" %>
              </div>
              <div class="col-sm-6 no-padding bottom-padding">
              <%= f.text_field :last_name, placeholder: 'Surname', class: "form-control" %>
              </div>
            </div>         
            <div class="form-group no-padding">
              <div class="col-sm-6 no-padding right-padding bottom-padding">
              <%= f.email_field :email, placeholder: 'Email address', class: "form-control" %>
              </div>
              <div class="col-sm-6 no-padding bottom-padding">
              <%= f.text_field :user_name,  placeholder: 'User name', required: true, class: "form-control" %>
              </div>
            </div> 
            <div class="form-group">
              <div class="col-sm-6 no-padding right-padding bottom-padding">
              <%= f.password_field :password, placeholder: 'New password', class: "form-control" %>
              </div>
              <div class="col-sm-6 no-padding bottom-padding">
              <%= f.password_field :password_confirmation, placeholder: 'Confirm password', class: "form-control" %>
              </div>
            </div>  
            <%= f.submit t('.sign_up', :default => "Sign up"), class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
  </div> 
</div> 

app/views/welcome/index.html.erb
<% if current_user %>
  <!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title><%= content_for?(:title) ? yield(:title) : "MyBook" %></title>
      <%= csrf_meta_tags %>
    </head>
    <body class="welcome-bg">
        <h3>Welcome, <%= current_user.full_name.present? ? current_user.first_name : current_user.email %></h3>
    </body>
  </html>

<% else %>

  <!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title><%= content_for?(:title) ? yield(:title) : "MyBook" %></title>
      <%= csrf_meta_tags %>
    </head>
    <body class="reg-bg">
      <%= render 'welcome/signup' %> 
    </body>
  </html>

<% end %>