config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => "user/registrations" }
  resources :users, only: [:show, :index, :destroy]
  resources :photos
  
  resources :photos do 
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end
  
  resources :posts, only: [:create, :destroy]
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :relationships, only: [:create, :destroy]

  root 'welcome#index'
  get ':user_name', to: 'users#show', as: :profile
  get ':user_name/following', to: 'users#following', as: :following
  get ':user_name/followers', to: 'users#followers', as: :followers
    

end

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    
    <%= link_to ("<i class='fa fa-book'></i> " +'My Book').html_safe, root_path, class: "navbar-brand" %>

      <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Profile", profile_path(current_user.user_name) %></li>
          <li><%= link_to "Photos", photos_path %></li>
          <li><%= link_to "Upload Photo", "photos/new" %></li>
          <li><%= link_to "Friends", "/path3"  %></li>
          <li><%= link_to "Twitter", "/path3"  %></li>
          <% if current_user.admin? %>
            <li><%= link_to "Users", users_path %></li>
          <% end %>
        </ul>
        
        <ul class="settings nav navbar-right col-md-4">
          <li class="col-md-8 user-name">
          <i class="fa fa-user"></i>
          <%= current_user.full_name.present? ? current_user.full_name : current_user.email %>
          </li>
          
          <li class="dropdown-toggle pull-left">
          <a href="#", title="Settings" data-toggle="dropdown" role="button"><i class='fa fa-cog'></i><span class="caret"></span></a>
          <ul class="dropdown-menu sub-menu">
            <li><%= link_to "Account", profile_path(current_user.user_name) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Privacy", profile_path(current_user.user_name) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Themes", profile_path(current_user.user_name) %></li>
          </ul>
          </li>
          <%= link_to('Log Out', destroy_user_session_path, class: 'btn btn-logout pull-right', method: :delete) %>
        </ul>
       
      </div>
  </div>
</div>



  
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MyBook" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
     
    <% if current_user %>
      <%= render 'layouts/navigation' %>
    <% else %>
      <%= render 'welcome/login' %>
    <% end %>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
        <%# shows flash messages when you login, logout, create, edit, or delete %>
        <%= bootstrap_flash %>
        <%= yield %>
        </div>
      </div>
    
      <footer>
        <p>&copy; Company 2016</p>
      </footer>
    </div>
  </body>
</html>